name: Build Project and Publish to itch.io
on: [push]
jobs:
  build:
    name: Build Project and Publish to itch.io ✨
    runs-on: ubuntu-latest
    concurrency:
      group: unity-build
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: '${{ secrets.UNITY_EMAIL }}'
          UNITY_PASSWORD: '${{ secrets.UNITY_PASSWORD }}'
          UNITY_SERIAL: '${{ secrets.UNITY_SERIAL }}'
        with:
          targetPlatform: StandaloneWindows
          unityVersion: 2020.3.18f1
      # - name: Return license
      #   uses: game-ci/unity-return-license@v1
      #   if: always()
      - uses: actions/upload-artifact@v2
        with:
          name: Adrenarun_Build_Windows
          path: build
      # Upload to Itch
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: Adrenarun
          ITCH_USER: azhu
          PACKAGE: build/StandaloneWindows